/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controller.MovieScheduleRoomDAO;
import Models.Movie;
import Models.MovieScheduleRoom;
import Models.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FilmBookingNoRealse extends javax.swing.JPanel {

    private JLabel[][] labels = new JLabel[5][5];
    /**
     * Creates new form FilmBooking
     * @param movie
     */
//    private Movie movie;
//
//    public void setMovie(Movie m) {
//        this.movie = m;
//        lblName.setText(lblName.getText() + movie.getMovieName());
//        lblGenres.setText(lblGenres.getText() + movie.getMovieGenres());
//        lblDesc.setText(lblDesc.getText() + movie.getMovieDescription());
//        lblCens.setText(lblCens.getText() + movie.getMovieCens());
//        lblLength.setText(lblLength.getText() + movie.getMovieLength());
//        lblRealease.setText(String.valueOf(movie.getMovieRelease()));
//    }
    private Movie currentMovie;
    private User curtentUser;
    public FilmBookingNoRealse(Movie movie, User user) {
        currentMovie = movie;
        initComponents();
        if(movie != null){
            lblName.setText(lblName.getText() + movie.getMovieName());
            lblGenres.setText(lblGenres.getText() + movie.getMovieGenres());
            lblDesc.setText(lblDesc.getText() + movie.getMovieDescription());
            lblCens.setText(lblCens.getText() + movie.getMovieCens());
            lblLength.setText(lblLength.getText() + movie.getMovieLength() + " phút");
            lblRealease.setText(lblRealease.getText() + String.valueOf(movie.getMovieRelease()));
            String imageUrl = movie.getMoviePoster();
            // Tạo ImageIcon từ URL
            if(!"".equals(imageUrl)){
                lblPhoto.setText("");
                ImageIcon icon = new ImageIcon(getClass().getResource(imageUrl));
                Image img = icon.getImage().getScaledInstance(165, 231, Image.SCALE_SMOOTH);
                lblPhoto.setIcon(new ImageIcon(img));
            }
            // Get Data
            
        }
    }
    
    
    private static ImageIcon createImageFromURL(String imageUrl) {
        try {
            // Chuyển URL thành ImageIcon
            URL url = new URL(imageUrl);
            return new ImageIcon(url);
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhoto = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGenres = new javax.swing.JLabel();
        lblLength = new javax.swing.JLabel();
        lblRealease = new javax.swing.JLabel();
        lblCens = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();

        setAutoscrolls(true);

        lblPhoto.setText("jLabel1");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName.setText("Tên phim: ");
        lblName.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblGenres.setText("Thể loại: ");

        lblLength.setText("Độ dài: ");

        lblRealease.setText("Ngày phát hành: ");

        lblCens.setText("Độ tuổi tối thiểu: ");

        lblDesc.setText("Description: ");
        lblDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLength)
                        .addGap(107, 107, 107)
                        .addComponent(lblCens))
                    .addComponent(lblRealease)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenres)
                    .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGenres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLength)
                            .addComponent(lblCens))
                        .addGap(18, 18, 18)
                        .addComponent(lblRealease))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCens;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblGenres;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblRealease;
    // End of variables declaration//GEN-END:variables
}
