/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.UIHelper;
import Models.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author nguye
 */
public class FrmStaffMain extends javax.swing.JFrame {
    private User user;
    /**
     * Creates new form FrmAdminMain
     */
    public Color color;
    
    public FrmStaffMain(User curentUser) {
        user = curentUser;
        initComponents();
        color = btnColor1.getBackground();
//        UIHelper.setAppLogo(this);
//        this.setTitle("DDL Cinema");
        this.setResizable(false);
        String[] words = curentUser.getFullname().split(" ");
        lblAdmin.setText(lblAdmin.getText() + words[words.length - 1]);
        
//        lblPhimRac.setVisible(false);
//        lblUserRac.setVisible(false);
//        lblLichRac.setVisible(false);
//        lblPhongRac.setVisible(false);
        updateLabelState(lblDatVe);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUserPhim(user));
    }
    public FrmStaffMain() {
        initComponents();
        color = btnColor1.getBackground();
        this.setResizable(false);
//        lblPhimRac.setVisible(false);
//        lblUserRac.setVisible(false);
//        lblLichRac.setVisible(false);
//        lblPhongRac.setVisible(false);
        updateLabelState(lblDatVe);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUserPhim(user));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPhim = new javax.swing.JLabel();
        lblLich = new javax.swing.JLabel();
        lblPhong = new javax.swing.JLabel();
        btnColor2 = new javax.swing.JButton();
        btnColor3 = new javax.swing.JButton();
        btnColor4 = new javax.swing.JButton();
        btnColor5 = new javax.swing.JButton();
        btnColor1 = new javax.swing.JButton();
        lblCDTK = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblDatVe = new javax.swing.JLabel();
        lblBanDoAn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setMaximumSize(new java.awt.Dimension(717, 515));
        pnlMain.setMinimumSize(new java.awt.Dimension(621, 476));
        pnlMain.setOpaque(false);
        pnlMain.setPreferredSize(new java.awt.Dimension(717, 515));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText(" Quản lý khách hàng");
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });

        lblPhim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhim.setForeground(new java.awt.Color(255, 255, 255));
        lblPhim.setText(" Quản lý phim");
        lblPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhimMouseClicked(evt);
            }
        });

        lblLich.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLich.setForeground(new java.awt.Color(255, 255, 255));
        lblLich.setText(" Quản lý lịch chiếu");
        lblLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLichMouseClicked(evt);
            }
        });

        lblPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblPhong.setText(" Quản lý phòng chiếu");
        lblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhongMouseClicked(evt);
            }
        });

        btnColor2.setBackground(new java.awt.Color(102, 0, 102));
        btnColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor2ActionPerformed(evt);
            }
        });

        btnColor3.setBackground(new java.awt.Color(153, 0, 0));
        btnColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor3ActionPerformed(evt);
            }
        });

        btnColor4.setBackground(new java.awt.Color(102, 102, 0));
        btnColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor4ActionPerformed(evt);
            }
        });

        btnColor5.setBackground(new java.awt.Color(0, 102, 51));
        btnColor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor5ActionPerformed(evt);
            }
        });

        btnColor1.setBackground(new java.awt.Color(0, 102, 102));
        btnColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor1ActionPerformed(evt);
            }
        });

        lblCDTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCDTK.setForeground(new java.awt.Color(255, 255, 255));
        lblCDTK.setText(" Cài đặt tài khoản");
        lblCDTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCDTKMouseClicked(evt);
            }
        });

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblHoaDon.setText(" Quản lý hóa đơn vé");
        lblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseClicked(evt);
            }
        });

        lblAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setText("Nhân viên: ");

        lblDatVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDatVe.setForeground(new java.awt.Color(255, 255, 255));
        lblDatVe.setText(" Đặt vé cho khách");
        lblDatVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDatVeMouseClicked(evt);
            }
        });

        lblBanDoAn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBanDoAn.setForeground(new java.awt.Color(255, 255, 255));
        lblBanDoAn.setText(" Quản lý đồ ăn đã đặt");
        lblBanDoAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanDoAnMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/movie1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schedule.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticket.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/food.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCDTK)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblBanDoAn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(lblHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPhim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDatVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnColor5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lblAdmin)
                                                        .addGap(71, 71, 71)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                            .addComponent(jLabel1)
                                                            .addComponent(lblDatVe))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLich)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPhong))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHoaDon))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBanDoAn))
                    .addComponent(jLabel7))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCDTK)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateLabelState(JLabel selectedLabel) {
        // Đặt các nhãn khác thành không hiển thị nền
        lblPhim.setOpaque(false);
        lblLich.setOpaque(false);
        lblPhong.setOpaque(false);
        lblUser.setOpaque(false);
        lblDatVe.setOpaque(false);
        lblBanDoAn.setOpaque(false);
//        lblRac.setOpaque(false);
//        lblPhimRac.setOpaque(false);
//        lblUserRac.setOpaque(false);
//        lblLichRac.setOpaque(false);
//        lblPhongRac.setOpaque(false);
        lblHoaDon.setOpaque(false);
        lblCDTK.setOpaque(false);
        
        // Đặt nhãn đã chọn thành hiển thị nền
        selectedLabel.setOpaque(true);
        selectedLabel.setBackground(color);

        //Đóng menu con nếu chọn sang lbl khác

        // Cập nhật lại giao diện
        lblDatVe.repaint();
        lblPhim.repaint();
        lblLich.repaint();
        lblPhong.repaint();
        lblUser.repaint();
//        lblRac.repaint();
//        lblPhimRac.repaint();
//        lblUserRac.repaint();
//        lblLichRac.repaint();
//        lblPhongRac.repaint();
        lblHoaDon.repaint();
        lblCDTK.repaint();
        lblBanDoAn.repaint();
    }
    
    public void closeChildMenu(){
//        if(lblPhimRac.isVisible()){
//            lblPhimRac.setVisible(false);
//            lblUserRac.setVisible(false);
//            lblLichRac.setVisible(false);
//            lblPhongRac.setVisible(false);
//        }else{
//            lblPhimRac.setVisible(true);
//            lblUserRac.setVisible(true);
//            lblLichRac.setVisible(true);
//            lblPhongRac.setVisible(true);
//        }
    }
    
    public void rePaint(){
        lblPhim.setBackground(color);
        lblLich.setBackground(color);
        lblPhong.setBackground(color);
        lblUser.setBackground(color);
        lblDatVe.setBackground(color);
//        lblRac.setBackground(color);
//        lblPhimRac.setBackground(color);
//        lblUserRac.setBackground(color);
//        lblLichRac.setBackground(color);
//        lblPhongRac.setBackground(color);
        lblCDTK.setBackground(color);
        lblPhim.repaint();
        lblLich.repaint();
        lblPhong.repaint();
        lblUser.repaint();
        lblBanDoAn.repaint();
//        lblRac.repaint();
//        lblPhimRac.repaint();
//        lblUserRac.repaint();
//        lblLichRac.repaint();
//        lblPhongRac.repaint();
        lblCDTK.repaint();
    }
    private void btnColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor1ActionPerformed
        color = btnColor1.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor1ActionPerformed

    private void btnColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor2ActionPerformed
        color = btnColor2.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor2ActionPerformed

    private void btnColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor3ActionPerformed
        color = btnColor3.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor3ActionPerformed

    private void btnColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor4ActionPerformed
        color = btnColor4.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor4ActionPerformed

    private void btnColor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor5ActionPerformed
        color = btnColor5.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor5ActionPerformed

    private void setForm(JComponent c){
        pnlMain.removeAll(); //Xoá toàn bộ các thành phần
        pnlMain.add(c); //Thêm form
        pnlMain.repaint(); //Cập nhật lại giao diện
        pnlMain.revalidate(); //Cập nhật lại bố cục
    }
    
    private void lblPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhimMouseClicked
        updateLabelState(lblPhim);
        pnlMain.setLayout(new BorderLayout());
        try {
            setForm(new PnlAdPhim());
        } catch (SQLException ex) {
            Logger.getLogger(FrmStaffMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmStaffMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblPhimMouseClicked

    private void lblLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichMouseClicked
        updateLabelState(lblLich);
        pnlMain.setLayout(new BorderLayout());
        try {
            setForm(new PnlAdLich());
        } catch (SQLException ex) {
            Logger.getLogger(FrmStaffMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmStaffMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblLichMouseClicked

    private void lblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongMouseClicked
        updateLabelState(lblPhong);
        pnlMain.setLayout(new BorderLayout());
        try {
            setForm(new PnlAdPhong());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmStaffMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmStaffMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblPhongMouseClicked
    
    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        try {
            updateLabelState(lblUser);
            pnlMain.setLayout(new BorderLayout()); 
            setForm(new PnlStaffAcc());
        } catch (SQLException ex) {
            Logger.getLogger(FrmStaffMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmStaffMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseClicked
        updateLabelState(lblHoaDon);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlAdHoaDon()); 
    }//GEN-LAST:event_lblHoaDonMouseClicked

    private void lblCDTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCDTKMouseClicked
        updateLabelState(lblCDTK);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlCaiDatTaiKhoan(user));
    }//GEN-LAST:event_lblCDTKMouseClicked

    private void lblDatVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatVeMouseClicked
        // TODO add your handling code here:
//        if(curentUser == null){
//            System.out.println("Không tìm thấy user ở Main");
//        }
        updateLabelState(lblDatVe);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUserPhim(user));//        updateLabelState(lblPhimDangChieu);
//        pnlMain.setLayout(new BorderLayout());
//        setForm(new PnlUserPhim(curentUser));
    }//GEN-LAST:event_lblDatVeMouseClicked

    private void lblBanDoAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanDoAnMouseClicked
        // TODO add your handling code here:
        updateLabelState(lblBanDoAn);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlAdDoAn());//    
    }//GEN-LAST:event_lblBanDoAnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStaffMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStaffMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor1;
    private javax.swing.JButton btnColor2;
    private javax.swing.JButton btnColor3;
    private javax.swing.JButton btnColor4;
    private javax.swing.JButton btnColor5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblBanDoAn;
    private javax.swing.JLabel lblCDTK;
    private javax.swing.JLabel lblDatVe;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblLich;
    private javax.swing.JLabel lblPhim;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
