package Views;

import Models.User;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JLabel;


public class FrmUserMain extends javax.swing.JFrame {
    private User curentUser;
    public FrmUserMain(User user) {
        initComponents();
        curentUser = user;
        String[] words = user.getFullname().split(" ");
        lblUser.setText(lblUser.getText() + words[words.length - 1]);
        color = btnColor1.getBackground();
        this.setResizable(false);
        setUser(user);
        updateLabelState(lblPhimDangChieu);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUserPhim(curentUser));
    }
    public void setUser(User user){
        curentUser = user;
    }
    public FrmUserMain() {
        initComponents();
        System.out.println("Khoi tao kh tham so");
//        color = btnColor1.getBackground();
        this.setResizable(false);
        updateLabelState(lblPhimDangChieu);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUserPhim(curentUser));
        
        updateLabelState(lblPhimDangChieu);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUserPhim(curentUser));
        
    }

    public Color color;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        lblPhimDangChieu = new javax.swing.JLabel();
        lblVe = new javax.swing.JLabel();
        btnColor2 = new javax.swing.JButton();
        btnColor3 = new javax.swing.JButton();
        btnColor4 = new javax.swing.JButton();
        btnColor5 = new javax.swing.JButton();
        btnColor1 = new javax.swing.JButton();
        lblCDTK = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPhimSapChieu = new javax.swing.JLabel();
        lblTatCaPhim = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDoAnDaDat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblPhimDangChieu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhimDangChieu.setForeground(new java.awt.Color(255, 255, 255));
        lblPhimDangChieu.setText("Phim đang chiếu");
        lblPhimDangChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhimDangChieuMouseClicked(evt);
            }
        });

        lblVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVe.setForeground(new java.awt.Color(255, 255, 255));
        lblVe.setText("Vé đã đặt");
        lblVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVeMouseEntered(evt);
            }
        });

        btnColor2.setBackground(new java.awt.Color(102, 0, 102));
        btnColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor2ActionPerformed(evt);
            }
        });

        btnColor3.setBackground(new java.awt.Color(153, 0, 0));
        btnColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor3ActionPerformed(evt);
            }
        });

        btnColor4.setBackground(new java.awt.Color(102, 102, 0));
        btnColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor4ActionPerformed(evt);
            }
        });

        btnColor5.setBackground(new java.awt.Color(0, 102, 51));
        btnColor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor5ActionPerformed(evt);
            }
        });

        btnColor1.setBackground(new java.awt.Color(0, 102, 102));
        btnColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor1ActionPerformed(evt);
            }
        });

        lblCDTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCDTK.setForeground(new java.awt.Color(255, 255, 255));
        lblCDTK.setText("Cài đặt tài khoản");
        lblCDTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCDTKMouseClicked(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Xin chào: ");

        lblPhimSapChieu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhimSapChieu.setForeground(new java.awt.Color(255, 255, 255));
        lblPhimSapChieu.setText("Phim sắp chiếu");
        lblPhimSapChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhimSapChieuMouseClicked(evt);
            }
        });

        lblTatCaPhim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTatCaPhim.setForeground(new java.awt.Color(255, 255, 255));
        lblTatCaPhim.setText("Tất cả phim");
        lblTatCaPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTatCaPhimMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/movie1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/movie2.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/movie3.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticket.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account.png"))); // NOI18N

        lblDoAnDaDat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDoAnDaDat.setForeground(new java.awt.Color(255, 255, 255));
        lblDoAnDaDat.setText("Đồ ăn đã đặt");
        lblDoAnDaDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoAnDaDatMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/food.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCDTK)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTatCaPhim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPhimSapChieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPhimDangChieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDoAnDaDat)
                                .addGap(0, 50, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblUser)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPhimDangChieu)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(lblPhimSapChieu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTatCaPhim)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(lblVe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDoAnDaDat)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCDTK)
                    .addComponent(jLabel5))
                .addGap(249, 249, 249)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pnlMain.setMaximumSize(new java.awt.Dimension(717, 515));
        pnlMain.setMinimumSize(new java.awt.Dimension(621, 476));
        pnlMain.setOpaque(false);
        pnlMain.setPreferredSize(new java.awt.Dimension(717, 515));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateLabelState(JLabel selectedLabel) {
        // Đặt các nhãn khác thành không hiển thị nền
        lblVe.setOpaque(false);
        lblPhimDangChieu.setOpaque(false);
        lblPhimSapChieu.setOpaque(false);
        lblTatCaPhim.setOpaque(false);
        lblCDTK.setOpaque(false);
        lblDoAnDaDat.setOpaque(false);

        // Đặt nhãn đã chọn thành hiển thị nền
        selectedLabel.setOpaque(true);
        selectedLabel.setBackground(color);

        //Đóng menu con nếu chọn sang lbl khác

        // Cập nhật lại giao diện
        lblVe.repaint();
        lblPhimDangChieu.repaint();
        lblPhimSapChieu.repaint();
        lblTatCaPhim.repaint();
        lblDoAnDaDat.repaint();
        lblCDTK.repaint();
    }
    
    private void setForm(JComponent c){
        pnlMain.removeAll(); //Xoá toàn bộ các thành phần
        pnlMain.add(c); //Thêm form
        pnlMain.repaint(); //Cập nhật lại giao diện
        pnlMain.revalidate(); //Cập nhật lại bố cục
    }
    
    public void rePaint(){
        lblVe.setBackground(color);
        lblPhimDangChieu.setBackground(color);
        lblVe.repaint();
        lblPhimDangChieu.repaint();
    }
    
    private void lblPhimDangChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhimDangChieuMouseClicked
        if(curentUser == null){
            System.out.println("Không tìm thấy user ở Main");
        }
        updateLabelState(lblPhimDangChieu);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUserPhim(curentUser));
        
    }//GEN-LAST:event_lblPhimDangChieuMouseClicked

    private void lblVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeMouseClicked
//        updateLabelState(lblVe);
//        pnlMain.setLayout(new BorderLayout());
//        setForm(new PnlChoNgoi());
        updateLabelState(lblVe);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUsVeDaDat(curentUser));

    }//GEN-LAST:event_lblVeMouseClicked

    private void btnColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor2ActionPerformed
        color = btnColor2.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor2ActionPerformed

    private void btnColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor3ActionPerformed
        color = btnColor3.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor3ActionPerformed

    private void btnColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor4ActionPerformed
        color = btnColor4.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor4ActionPerformed

    private void btnColor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor5ActionPerformed
        color = btnColor5.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor5ActionPerformed

    private void btnColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor1ActionPerformed
        color = btnColor1.getBackground();
        rePaint();
    }//GEN-LAST:event_btnColor1ActionPerformed

    private void lblVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVeMouseEntered

    private void lblCDTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCDTKMouseClicked
        // TODO add your handling code here:
        updateLabelState(lblCDTK);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlCaiDatTaiKhoan(curentUser));
    }//GEN-LAST:event_lblCDTKMouseClicked

    private void lblPhimSapChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhimSapChieuMouseClicked
        // TODO add your handling code here:
        updateLabelState(lblPhimSapChieu);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlPhimSapChieu(curentUser));
    }//GEN-LAST:event_lblPhimSapChieuMouseClicked

    private void lblTatCaPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTatCaPhimMouseClicked
        // TODO add your handling code here:
        updateLabelState(lblTatCaPhim);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlTatCaPhim(curentUser));
    }//GEN-LAST:event_lblTatCaPhimMouseClicked

    private void lblDoAnDaDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoAnDaDatMouseClicked
        // TODO add your handling code here:
        updateLabelState(lblDoAnDaDat);
        pnlMain.setLayout(new BorderLayout());
        setForm(new PnlUsDoAnDaDat(curentUser));
    }//GEN-LAST:event_lblDoAnDaDatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUserMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor1;
    private javax.swing.JButton btnColor2;
    private javax.swing.JButton btnColor3;
    private javax.swing.JButton btnColor4;
    private javax.swing.JButton btnColor5;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCDTK;
    private javax.swing.JLabel lblDoAnDaDat;
    private javax.swing.JLabel lblPhimDangChieu;
    private javax.swing.JLabel lblPhimSapChieu;
    private javax.swing.JLabel lblTatCaPhim;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVe;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
