/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controller.FoodDetailsDAO;
import Models.FoodDetails;
import Models.User;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class PnlAdDoAn extends javax.swing.JPanel {

    /**
     * Creates new form PnlAdDoAn
     */
    public PnlAdDoAn(){
        initComponents();
        try {
            showData();
        } catch (SQLException ex) {
            Logger.getLogger(PnlAdDoAn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PnlAdDoAn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDoAn = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNgayDat = new javax.swing.JTable();

        tbDoAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên đồ ăn kèm", "Số lượng", "Tổng tiền đã thanh toán", "Ngày đặt", "Mã người dùng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbDoAn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbDoAnAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbDoAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDoAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDoAn);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Danh sách hoá đơn đồ ăn");

        tbNgayDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Ngày đặt"
            }
        ));
        tbNgayDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNgayDatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbNgayDat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbDoAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDoAnMouseClicked
        
    }//GEN-LAST:event_tbDoAnMouseClicked
    public void showDetail(LocalDate date){
        // Model của bảng tbBooking
        DefaultTableModel model = (DefaultTableModel) tbDoAn.getModel();
        model.setRowCount(0); // Xóa các dòng cũ trong bảng tbBooking

        FoodDetailsDAO FoodDetailsDAO = new FoodDetailsDAO();
        // getFoodBookingByDateAndUserId
        for (FoodDetails foodDetails : FoodDetailsDAO.getFoodBookingByDate(date)) {
            Object[] row = new Object[5];
            row[0] = foodDetails.getFoodName();
            row[1] = foodDetails.getQuantity();
            row[2] = foodDetails.getPrice();
            row[3] = foodDetails.getBookingDate();
            row[4] = foodDetails.getUserId();

            // Thêm dòng vào bảng tbBooking
            model.addRow(row);
        }
    }
    
    public void showData() throws SQLException, ClassNotFoundException {
        // Model của bảng tbBooking
        DefaultTableModel model = (DefaultTableModel) tbNgayDat.getModel();
        model.setRowCount(0); // Xóa các dòng cũ trong bảng tbBooking

        // Lấy dữ liệu hóa đơn đồ ăn
        FoodDetailsDAO FoodDetailsDAO = new FoodDetailsDAO();
        for (LocalDate date : FoodDetailsDAO.getDistinctBookingDates()) {
//            if(currentUser.getUserId() != foodDetails.getUserId()){
//                break;
//            }
            Object[] row = new Object[1];
            row[0] = date;

            // Thêm dòng vào bảng tbBooking
            model.addRow(row);
        }
    }
    
    private void tbNgayDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNgayDatMouseClicked
        // TODO add your handling code here:
        int row = this.tbNgayDat.getSelectedRow();
        LocalDate date = (LocalDate) tbNgayDat.getValueAt(row, 0);
        showDetail(date);
    }//GEN-LAST:event_tbNgayDatMouseClicked

    private void tbDoAnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbDoAnAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDoAnAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDoAn;
    private javax.swing.JTable tbNgayDat;
    // End of variables declaration//GEN-END:variables
}
