/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controller.MovieDAO;
import Controller.UserDAO;
import Models.Movie;
import Models.User;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class PnlAdPhim extends javax.swing.JPanel {

    /**
     * Creates new form PnlAdPhim
     */
    public void showData() throws SQLException, ClassNotFoundException {
        DefaultTableModel model = (DefaultTableModel) tbPhim.getModel();
        model.setRowCount(0); // Xóa các dòng cũ trong bảng

        MovieDAO moviesDAO = new MovieDAO();
        List<Movie> movies = moviesDAO.getAllMovies();

        for (Movie movie : movies) {
            if(movie.getIsDeleted())
                continue;
            Object row[] = new Object[9];
            row[0] = movie.getMovieId();
            row[1] = movie.getMovieName();
            row[2] = movie.getMovieDescription();
            row[3] = movie.getMovieTrailer();
            row[4] = movie.getMovieCens();
            row[5] = movie.getMovieGenres();
            row[6] = movie.getMovieRelease();
            row[7] = movie.getMovieLength();
            row[8] = movie.getMoviePoster();
            // Thêm dòng vào bảng
            model.addRow(row);
        }
    }
    public void resetData() {
        txtTenPhim.setText("");
        txtThoiLuong.setText("");
        txtGioiHan.setText("");
        txtTheLoai.setText("");
        txtNgay.setText("");
        txtThang.setText("");
        txtNam.setText("");
        txtMoTa.setText("");
        txtFilmId.setText("");
        txtTrailer.setText("");
    }
    public PnlAdPhim() throws SQLException, ClassNotFoundException {
        initComponents();
        lblErrorTP.setText("");
        lblErrorTG.setText("");
        lblErrorGH.setText("");
        lblErrorTL.setText("");
        lblErrorNKC.setText("");
        lblErrorPoster.setText("");
        lblErrorMT.setText("");
        lblErrorTrailer.setText("");
        txtFilmId.setVisible(false);
        btnXoaTim.setEnabled(false);
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtThang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        txtTim = new javax.swing.JTextField();
        lblErrorTP = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        lblErrorNKC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblErrorMT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblErrorTG = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblErrorGH = new javax.swing.JLabel();
        lblErrorTL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblErrorPoster = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTenPhim = new javax.swing.JTextField();
        txtThoiLuong = new javax.swing.JTextField();
        txtTheLoai = new javax.swing.JTextField();
        txtGioiHan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPhim = new javax.swing.JTable();
        txtNgay = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtFilmId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblErrorTrailer = new javax.swing.JLabel();
        txtTrailer = new javax.swing.JTextField();
        btnChon = new javax.swing.JButton();
        lblPoster = new javax.swing.JLabel();
        btnXoaTim = new javax.swing.JButton();

        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Có thể thêm, xem, sửa, xoá");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm: ");

        txtTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTim.setOpaque(true);
        txtTim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimFocusGained(evt);
            }
        });
        txtTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimMouseClicked(evt);
            }
        });

        lblErrorTP.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorTP.setText("jLabel2");

        btnTim.setText("Tìm");
        btnTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimMouseClicked(evt);
            }
        });

        lblErrorNKC.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorNKC.setText("jLabel12");

        jLabel5.setText("Tên phim:");

        lblErrorMT.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMT.setText("jLabel13");

        jLabel6.setText("Ngày khởi chiếu: ");

        lblErrorTG.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorTG.setText("jLabel14");

        jLabel7.setText("Mô tả:");

        jLabel8.setText("Thể loại:");

        lblErrorGH.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorGH.setText("jLabel15");

        lblErrorTL.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorTL.setText("jLabel16");

        jLabel9.setText("Giới hạn:");

        lblErrorPoster.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPoster.setText("jLabel17");

        jLabel10.setText("Thời lượng:");

        txtGioiHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioiHanActionPerformed(evt);
            }
        });

        tbPhim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Phim ID", "Tên ", "Mô tả", "Trailer", "Giới hạn", "Thể loại", "Ngày khởi chiếu", "Thời lượng (phút)", "Poster"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhimMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPhim);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản lý danh sách phim");

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        jLabel2.setText("Poster:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtFilmId.setText("  ");

        jLabel11.setText("Trailer: ");

        lblErrorTrailer.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorTrailer.setText("jLabel2");

        btnChon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnChon.setText("Chọn ảnh");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        lblPoster.setText("Poster");

        btnXoaTim.setText("Reset");
        btnXoaTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaTimMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblErrorTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtTenPhim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(lblErrorNKC, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(36, 36, 36)
                                                        .addComponent(jLabel11))
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblErrorTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addComponent(txtTrailer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFilmId, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(lblErrorMT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblErrorPoster))
                            .addComponent(btnChon))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErrorGH, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTheLoai)
                                    .addComponent(txtGioiHan)
                                    .addComponent(txtThoiLuong)
                                    .addComponent(lblErrorTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorTG, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaTim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(btnXoaTim))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTim)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(lblErrorTL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtGioiHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(lblErrorTP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel6)
                                    .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErrorGH)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel10)
                                    .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorTG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnChon))
                                    .addComponent(lblPoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblErrorNKC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(lblErrorTrailer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFilmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblErrorMT)
                                    .addComponent(lblErrorPoster)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkTP(){
        if("".equals(txtTenPhim.getText())){
            lblErrorTP.setText("Tên phim bị trống");
            return false;
        }
        lblErrorTP.setText("");
        return true;
    }
    
    public boolean checkTG(){
        try{
            if(Integer.parseInt(txtThoiLuong.getText()) < 0){
                lblErrorTG.setText("Thời lượng âm");
                return false;
            }
            lblErrorTG.setText("");
            return true;
        }catch(Exception e){
            lblErrorTG.setText("Thời lượng bị trống");
            return false;
        }
    }
    
    public boolean checkGH(){
        try{
            if(Integer.parseInt(txtGioiHan.getText()) < 0){
                lblErrorGH.setText("Tuổi giới hạn âm");
                return false;
            }
            lblErrorGH.setText("");
            return true;
        }catch(Exception e){
            lblErrorGH.setText("Tuổi giới hạn bị trống");
            return false;
        }
    }
    
    public boolean checkTL(){
        if("".equals(txtTheLoai.getText())){
            lblErrorTL.setText("Tên phim bị trống");
            return false;
        }
        lblErrorTL.setText("");
        return true;
    }
    public boolean checkTrailer(){
        if("".equals(txtTrailer.getText())){
            lblErrorTrailer.setText("Trailer bị trống");
            return false;
        }
        lblErrorTrailer.setText("");
        return true;
    }
    
    public boolean checkNKC(){
        try{
            int day = Integer.parseInt(txtNgay.getText());
            int month = Integer.parseInt(txtThang.getText());
            int year = Integer.parseInt(txtNam.getText());
            LocalDate currentDate = LocalDate.now();
            boolean isLeapYear = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);

            // Số ngày trong các tháng
            int[] daysInMonth = {31, 28 + (isLeapYear ? 1 : 0), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

            // Kiểm tra tháng
            if (month < 1 || month > 12) {
                lblErrorNKC.setText("Tháng không hợp lệ. ");
                return false;
            }
               
            // Kiểm tra ngày
            if (day < 1 || day > daysInMonth[month - 1]) {
                lblErrorNKC.setText("Ngày không hợp lệ. ");
                return false;
            }
                
            // Kiểm tra năm
            if(year < 1900 || year > currentDate.getYear() + 1){
                lblErrorNKC.setText("Năm nhập không hợp lệ. ");
                return false;
            }
            
            lblErrorNKC.setText("");
            return true;
        }catch(Exception e){
            lblErrorNKC.setText("Ngày bị bỏ trống hoặc sai định dạng. ");
            return false;
        }
    }
    
    public boolean checkMT(){
        if("".equals(txtMoTa.getText())){
            lblErrorMT.setText("Mô tả phim bị trống");
            return false;
        }
        lblErrorMT.setText("");
        return true;
    }
    
    public boolean checkPoster(){
        if("".equals(path)){
            lblErrorPoster.setText("Poster bị trống");
            return false;
        }
        return true;
    }
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        boolean error = checkTP() && checkNKC() && checkMT() && checkTL() && checkGH() && checkTG() && checkTrailer();
        if(error)
        {
            int id = Integer.parseInt(txtFilmId.getText());
            String name = txtTenPhim.getText();
            String desc = txtMoTa.getText();
            String trailer = txtTrailer.getText();
            String genres = txtTheLoai.getText();
            int cens = Integer.parseInt(txtGioiHan.getText());
            int day = Integer.parseInt(txtNgay.getText());
            int month = Integer.parseInt(txtThang.getText());
            int year = Integer.parseInt(txtNam.getText());
            LocalDate date = LocalDate.of(year, month, day);
            int length = Integer.parseInt(txtThoiLuong.getText());
            MovieDAO movieDAO = new MovieDAO();
            boolean result = movieDAO.updateMovieById(id, name, desc, trailer, cens, genres, date, length, path);
            if(result){
                try {
                    resetData();
                    showData();
                } catch (SQLException ex) {
                    Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtGioiHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGioiHanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGioiHanActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        boolean error = checkTP() && checkNKC() && checkMT() && checkTL() && checkGH() && checkTG() && checkTrailer();
        if(error) {
            String name = txtTenPhim.getText();
            String desc = txtMoTa.getText();
            String trailer = txtTrailer.getText();
            String genres = txtTheLoai.getText();
            int cens = Integer.parseInt(txtGioiHan.getText());
            int day = Integer.parseInt(txtNgay.getText());
            int month = Integer.parseInt(txtThang.getText());
            int year = Integer.parseInt(txtNam.getText());
            LocalDate date = LocalDate.of(year, month, day);
            int length = Integer.parseInt(txtThoiLuong.getText());
            MovieDAO movieDAO = new MovieDAO();
            try {
                boolean result = movieDAO.addMovie(name, desc, trailer, cens, genres, date, length, path);
                if(result){
                    resetData();
                    showData();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int response = JOptionPane.showConfirmDialog(
            null,
            "Bạn có chắc chắn muốn xoá?",
            "Xác nhận",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            // Hành động khi người dùng chọn Yes
            int id = Integer.parseInt(txtFilmId.getText());
            MovieDAO movieDAO = new MovieDAO();
            boolean result = movieDAO.softDeleteMovieById(id);
            if(result){
                resetData();
                try {
                    showData();
                } catch (SQLException ex) {
                    Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        } else if (response == JOptionPane.NO_OPTION) {
            // Hành động khi người dùng chọn No
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tbPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhimMouseClicked
        // TODO add your handling code here:
        int row =this.tbPhim.getSelectedRow();
        int id = Integer.parseInt(this.tbPhim.getModel().getValueAt(row, 0).toString());
        String name = this.tbPhim.getModel().getValueAt(row,1).toString();
        String desc = this.tbPhim.getModel().getValueAt(row,2).toString();
        String trailer = this.tbPhim.getModel().getValueAt(row,3).toString();
        String cens = this.tbPhim.getModel().getValueAt(row,4).toString();
        String genres = this.tbPhim.getModel().getValueAt(row,5).toString();
        String dateStr = this.tbPhim.getModel().getValueAt(row, 6).toString();
        LocalDate date = LocalDate.parse(dateStr);
        String length =this.tbPhim.getModel().getValueAt(row, 7).toString();
        String poster = this.tbPhim.getModel().getValueAt(row, 8).toString();
        lblPoster.setText("");
        ImageIcon icon = new ImageIcon(getClass().getResource(poster));
        int width = lblPoster.getWidth() > 0 ? lblPoster.getWidth() : 68; // Giá trị mặc định
        int height = lblPoster.getHeight() > 0 ? lblPoster.getHeight() : 87; // Giá trị mặc định
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        lblPoster.setIcon(new ImageIcon(img));
        lblPoster.repaint();
        txtFilmId.setText(String.valueOf(id));
        txtTenPhim.setText(name);
        txtMoTa.setText(desc);
        txtTrailer.setText(trailer);
        txtGioiHan.setText(cens);
        txtTheLoai.setText(genres);
        txtNgay.setText(String.valueOf(date.getDayOfMonth()));
        txtThang.setText(String.valueOf(date.getMonthValue()));
        txtNam.setText(String.valueOf(date.getYear()));
        txtThoiLuong.setText(length);
    }//GEN-LAST:event_tbPhimMouseClicked

    public String path = "";
    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        try {
            // Mở JFileChooser để chọn ảnh
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn poster phim");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Hình ảnh", "jpg", "jpeg", "png");
            fileChooser.setFileFilter(filter);

            int result = fileChooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                // Lấy file được chọn
                File selectedFile = fileChooser.getSelectedFile();
                String sourcePath = selectedFile.getAbsolutePath();

                String folderPath = "src/main/resources/images"; // Thư mục chứa ảnh
                // Tạo đường dẫn đích (tên file trong folder images)
                String destinationPath = folderPath + File.separator + selectedFile.getName();
                File destinationFile = new File(destinationPath);

                // Sao chép file vào thư mục đích
                Files.copy(Paths.get(sourcePath), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

                // Gán đường dẫn (sau này lưu vào cơ sở dữ liệu)
                path = "/images/" + selectedFile.getName();

                // Hiển thị ảnh trên JLabel
                ImageIcon icon = new ImageIcon(destinationFile.getAbsolutePath());
                Image img = icon.getImage().getScaledInstance(lblPoster.getWidth(), lblPoster.getHeight(), Image.SCALE_SMOOTH);
                lblPoster.setIcon(new ImageIcon(img));

                System.out.println("Ảnh đã lưu vào: " + destinationPath);
            } else {
                System.out.println("Người dùng đã hủy chọn file.");
            }
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Có lỗi xảy ra khi sao chép file.");
        }
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimMouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) tbPhim.getModel();
            model.setRowCount(0); // Xóa các dòng cũ trong bảng
            
            MovieDAO moviesDAO = new MovieDAO();
            Movie movie = moviesDAO.getAllMoviesById(txtTim.getText());
            btnXoaTim.setEnabled(true);
            btnTim.setEnabled(false);
            if(movie != null)
                if(!movie.getIsDeleted()){
                    Object row[] = new Object[9];
                    row[0] = movie.getMovieId();
                    row[1] = movie.getMovieName();
                    row[2] = movie.getMovieDescription();
                    row[3] = movie.getMovieTrailer();
                    row[4] = movie.getMovieCens();
                    row[5] = movie.getMovieGenres();
                    row[6] = movie.getMovieRelease();
                    row[7] = movie.getMovieLength();
                    row[8] = movie.getMoviePoster();
                    // Thêm dòng vào bảng
                    model.addRow(row);
                    
                }
                else
                    return;
            else
                return;   
        } catch (SQLException ex) {
            Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTimMouseClicked

    private void btnXoaTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaTimMouseClicked
        try {
            showData();
            btnTim.setEnabled(true);
            btnXoaTim.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PnlAdPhim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaTimMouseClicked

    private void txtTimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimFocusGained
        // TODO add your handling code here:
//        if("Tên phim".equals(txtTim.getText())){
//            txtTim.setText("");
//        }
    }//GEN-LAST:event_txtTimFocusGained

    private void txtTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimMouseClicked
        // TODO add your handling code here:
//        if("Tên phim".equals(txtTim.getText())){
//            txtTim.setText("");
//        }
    }//GEN-LAST:event_txtTimMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorGH;
    private javax.swing.JLabel lblErrorMT;
    private javax.swing.JLabel lblErrorNKC;
    private javax.swing.JLabel lblErrorPoster;
    private javax.swing.JLabel lblErrorTG;
    private javax.swing.JLabel lblErrorTL;
    private javax.swing.JLabel lblErrorTP;
    private javax.swing.JLabel lblErrorTrailer;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JTable tbPhim;
    private javax.swing.JTextField txtFilmId;
    private javax.swing.JTextField txtGioiHan;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtTenPhim;
    private javax.swing.JTextField txtThang;
    private javax.swing.JTextField txtTheLoai;
    private javax.swing.JTextField txtThoiLuong;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTrailer;
    // End of variables declaration//GEN-END:variables
}
